### ISSUE TITLE
[Bug]: Wallet CLI does not allow full amount to be staked

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-sdk#2236]
### Issue description

```
Wallet "alias": begin-staking 0xb8f540d46a9ebddc6bec85dafbe157f56d4aac033c3d216f115242a6512eb0e8 1000000000 2
Stronghold password: [hidden]
Begin staking for 0xb8f540d46a9ebddc6bec85dafbe157f56d4aac033c3d216f115242a6512eb0e8.
`invalid stakes amount`
2024-04-26 07:49:47 (UTC) wallet::wallet_cli                         ERROR `invalid stakes amount`
```

The account in question has exactly `1000000000` tokens. Only after lowering it to `100000` did it work.

### Version

Branch from #2235.

### Expected behaviour

I should be able to stake the full amount in an account.

### Actual behaviour

The command failed with `invalid stakes amount`.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create an account with account id `id` with X tokens.
2. Run `begin-staking id X 1`.

### Errors

See above.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by DaughterOfMars** [comment]
This may be related to the missing requirement in the staking calls that is being fixed in #2235

**Comment by PhilippGackstatter** [comment]
Sorry, I noted the wrong commit I was using. I actually used the branch from the #2235 PR for testing this, so it's still present there. Updated the description.
